kind: PersistentVolume
apiVersion: v1
metadata:
 name: mongo-pv
 labels:
  type: local
spec:
 storageClassName: local-storage
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/app/mongodb/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: mongo-pv-claim
spec:
 storageClassName: local-storage
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 1Gi
