apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
        TZ: Shanghai
    spec:
      nodeSelector:
        traefik: "traefik"
      serviceAccountName: traefik-ingress-controller
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      volumes:
      - name: ssl
        secret:
          secretName: cert
      - name: config
        configMap:
          name: traefik-conf
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo
      - name: logdir
        hostPath:
          path: /app/applogs/traefik/
      containers:
      - image: traefik:v1.7.18
        name: traefik-ingress-lb
        env: 
        - name: TZ
          value: "Asia/Shanghai"
        volumeMounts:
        - mountPath: "/var/log"
          name: "logdir"
        - mountPath: "/ssl"
          name: "ssl"
        - mountPath: "/config"
          name: "config"
        - mountPath: "/usr/share/zoneinfo"
          name: "localtime"
        resources:
          limits:
            cpu: 2000m
            memory: 4096Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: web
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        - name: admin
          containerPort: 9002
        - name: metrics     
          protocol: TCP
          containerPort: 8080
        args:
        - --web
        - --kubernetes
        - --configfile=/config/traefik.toml
        - --logLevel=INFO
        - --web.metrics.prometheus
        - --web.metrics
        - --accesslog
        - --accesslog.filepath=/var/log/traefik_access.log
        - --accesslog.fields.names="StartLocal=keep StartUTC=drop"
        - --traefiklog
        - --traefiklog.filepath=/var/log/traefik.log
        - --traefiklogsfile=traefik.log
        - --api
