apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  baseImage: 10.204.57.39/common/alertmanager
  replicas: 2
  resources:
    requests:
      memory: "1000Mi"
      cpu: "1"
  serviceAccountName: alertmanager-main
  version: v0.15.1
